patrolCoordinates[1, 0] = x;
patrolCoordinates[1, 1] = 1902;
numPatrolPoints++;
patrolCoordinates[2, 0] = 2158;
patrolCoordinates[2, 1] = patrolCoordinates[1, 1];
numPatrolPoints++;
patrolCoordinates[3, 0] = patrolCoordinates[2, 0];
patrolCoordinates[3, 1] = y;
numPatrolPoints++;
patrolCoordinates[4, 0] = 2047;
patrolCoordinates[4, 1] = 1632;
numPatrolPoints++;
patrolCoordinates[5, 0] = 2415;
patrolCoordinates[5, 1] = patrolCoordinates[4, 1];
numPatrolPoints++;
patrolCoordinates[6, 0] = 2479;
patrolCoordinates[6, 1] = y;
numPatrolPoints++;
patrolCoordinates[7, 0] = patrolCoordinates[6, 0];
patrolCoordinates[7, 1] = patrolCoordinates[1, 1];
numPatrolPoints++;
patrolCoordinates[8, 0] = 2318;
patrolCoordinates[8, 1] = patrolCoordinates[1, 1];
numPatrolPoints++;
patrolCoordinates[9, 0] = patrolCoordinates[8, 0];
patrolCoordinates[9, 1] = y;
numPatrolPoints++;
patrolCoordinates[10, 0] = patrolCoordinates[5, 0];
patrolCoordinates[10, 1] = patrolCoordinates[5, 1];
numPatrolPoints++;
patrolCoordinates[11, 0] = patrolCoordinates[4, 0];
patrolCoordinates[11, 1] = patrolCoordinates[4, 1];
numPatrolPoints++;