patrolCoordinates[1, 0] = x;
patrolCoordinates[1, 1] = 550;
numPatrolPoints++;
patrolCoordinates[2, 0] = 4223;
patrolCoordinates[2, 1] = 381;
numPatrolPoints++;
patrolCoordinates[3, 0] = 4638;
patrolCoordinates[3, 1] = patrolCoordinates[1, 1];
numPatrolPoints++;
patrolCoordinates[4, 0] = patrolCoordinates[3, 0];
patrolCoordinates[4, 1] = y;
numPatrolPoints++;
patrolCoordinates[5, 0] = patrolCoordinates[2, 0];
patrolCoordinates[5, 1] = patrolCoordinates[2, 1];
numPatrolPoints++;